Merge 1.0.0 release branch changes into develop (#2190)
* Switch to 1.0.0-rc1

* Silence more nvcc warnings

* Add missing ALPAKA_UNREACHABLE
* Silence more warnings

Co-authored-by: Bernhard Manfred Gruber <bernhardmgruber@gmail.com>

* Disable activemask for SYCL

Fixes: #2124

* refactor template order `allocMappedBufIfSupported`

Move template `TPlatform` as the last template. There is no need to provide the platform template signature if we pass the platform as an instance.

* Remove unused aliases

* Only add clang warning flag when supported

* Fix a warning with nvcc

* Workaround gcc warning on uninitialized PlatformCpu

* Fix warnings by clang

* Suppress clang warnings in nvcc generated code

* Pass alpaka_ENABLE_WERROR from environment to CMake

* Disable GCC warning in nvcc generated code

Fixes the following warning:
```
/builds/hzdr/crp/alpaka/test/unit/math/src/Defines.hpp:52:35: error: left operand of comma operator has no effect [-Werror=unused-value]
   52 |                         for(size_t i = 0; i < argsItem.arity_nr; ++i)
      |                          ~~~~~~~~~^~~~~~~~~~
```

* Workaround gcc warning on uninitialized PlatformUniformCudaHipRt

* Fix OpenMP 5.1 atomics

* Workaround clang not recognizing ternay expression
* Implement atomicInc/atomicDec via omp critical

Fixes: #2170

* Add clang-17 to CI

Fixes: #2169

* Rename lambda captures to workaround warnings

clang warns that the names of the captures shadow the outside variables.
E.g.:

QueueUniformCudaHipRt.hpp:215:57: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
  215 |                 auto f = queue.m_callbackThread.submit([data = std::move(data)] { data->t(); });
      |                                                         ^

* Exclude clang CUDA Debug builds from the CI

They fail with:
ptxas /tmp/randomStrategies-sm_61-768a17.s, line 14415; fatal   : Parsing error near '.': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)

* Add clang-17 to README.md

CUDA/HIP/SYCL is marked as untested for now.

* Fix clang-format version in docs (#2176)

* Remove unnecessary -fintelfpga flag

* Add changelog for alpaka v1.0.0

* Update author lists

Co-authored-by: Bernhard Manfred Gruber <bernhardmgruber@gmail.com>

* Set release date in changelog

---------

Co-authored-by: Jan Stephan <j.stephan@hzdr.de>
Co-authored-by: René Widera <r.widera@hzdr.de>