HIP <=5.3 avoid compiler error
Avoid compile error for CI tests if the following warning from rocrand
is shown:

```
rocrand/rocrand_common.h:73:6: error: "Disabled inline asm, because the build target does not support it." [-Werror,-W#warnings]
    #warning "Disabled inline asm, because the build target does not support it."
```